### PR TITLE
Add preact info

### PR DESCRIPTION
**Pull request by joaomilho**

### CODE REVIEW

**Comment by joaomilho** [comment]
That's it

**Comment by xaviervia** [comment]
Should we add this info to the Getting Started page as well? I guess the README and Getting Started should more or less share the same info

**Comment by xaviervia** [comment]
On a more long term comment, we could probably literally put the same information: load the README with a markdown loader, pass it through html2react, :shipit:

**Comment by joaomilho** [comment]
?

**Comment by joaomilho** [comment]
ah, to the showcase, right!

**Comment by pirelenito** [comment]
This change should have been a major.

**Pull request merged**
