### PR TITLE
Add partial prop to the checkbox component

### LINKED ISSUE #297: Add "partially checked" status for checkbox
screen shot 2017-02-13 at 11 23 50

Ping @JoakimLofgren @hankatt

### PR DESCRIPTION
**Pull request by ChristerGustavsson**
Fixes #297

### CODE REVIEW

**Comment by JoakimLofgren** [comment]
partial-checkbox

**Comment by hannah-ahl** [comment]
The line seems to have a subpixel which makes it feel offset on the screenshot.
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by JoakimLofgren** [comment]
@hannah-ahl Yeah, seems to be subpixel rendering issues.. I though the svg viewport would've handled that more gracefully :(

@xaviervia Thoughts?

**Comment by xaviervia** [comment]
I’m not sure, I’m not seeing what you are seeing :( How should it look like?

**Comment by JoakimLofgren** [comment]
It looks a bit off-center in the screenshot. If you zoom in on the showroom it looks more centered.

**Comment by hannah-ahl** [comment]
Dun dun DUUUUUN


Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by hankatt** [comment]
Horizontal offset right? It's a bit closer to the right side than the left, no?

**Comment by xaviervia** [comment]
Wow, I measured and you are right. I still can barely see it xD
Will fix.

**Comment by xaviervia** [comment]
Nope, wait, this is an artefact of the screenshot. Doesn’t happen locally. I need a member of the Pixel Vision Team™

**Comment by xaviervia** [comment]
screen shot 2017-02-16 at 10 36 42

**Pull request merged**
