### PR TITLE
Fix fieldtooltip hover

### PR DESCRIPTION
**Pull request by kgilles**
Makes sure that the tooltip bubble stays visible when leaving the icon and entering the bubble itself.

### CODE REVIEW

**Comment by xaviervia** [comment]
Thanks for the example. Unfortunately the fix doesn’t seem to be working though.
tooltip-dissappears

**Comment by kgilles** [comment]
You have to go via the arrow. That's the best I could do with the Tooltip component as I couldn't figure out how to expand the Tooltip bubble surface closer to the icon without putting the entire thing too close to the icon itself.

**Comment by xaviervia** [comment]
One idea is to add a transparent `div` covering the area just below the bubble as part of the tooltip, something like:

artboard

That way the target area would be bigger and it would still be active if the mouse is in the vicinity.

What do you think?

**Comment by kgilles** [comment]
I'll see if I can make that happen.

**Comment by kgilles** [comment]
I added a transparent span below the bubble, but didn't make it 100% width because I felt like it shouldn't interfere too much with the space of the actual field it's inside.
screen shot 2017-06-05 at 11 38 04 am

**Pull request merged**
