### PR TITLE
Fix box selector structure

### PR DESCRIPTION
**Pull request by xaviervia**
> Addresses https://github.com/klarna/ui/issues/249 as well
> Addresses https://github.com/klarna/ui/issues/160 as well

Explanation will come later

### CODE REVIEW

**Comment by martinnorum** [comment]
@xaviervia I referenced #160 as well in your comment

**Comment by Nevon** [comment]
There's a lot of duplicated code between the two versions, and I'm quite certain that there's a bunch of logic that's no longer needed. For example, the highlight in the horizontal one could be implemented in pure CSS (or close to it at least) and get a well-needed performance boost.

Provided that the API contract stays, though, we could do that in a separate PR, since it will be pretty much a complete rewrite of at least the horizontal one.

**Comment by xaviervia** [comment]
@Nevon well, the new animation is not definitive. It doesn't look too good either. It was just a compromise to get a fix out of the door.

**Comment by xaviervia** [comment]
@Nevon the animation behavior will very likely change. We should sync with @hannah-ahl about that. I removed some of the unused code with @npejo 's blessing, but I'm aware there is more to do. If you are OK with postponing the CSS changes let's merge this now and iterate asap.

**Comment by farfalena** [comment]
I would opt for making this change available and creating a new issue for cleaning up the CSS.

**Comment by Nevon** [comment]
Go for it. I'll create a ticket for revisiting the implementation.

**Comment by Nevon** [comment]
Ticket created at #251

**Pull request merged**
