### PR TITLE
(WIP) Add calendar icon

### PR DESCRIPTION
**Pull request by JoakimLofgren**
For the upcoming date picker we need a calendar icon.
@hankatt Did we need to update the design any?

Preview of the showroom tiny section:
calendar-icon

### CODE REVIEW

**Comment by hankatt** [comment]
Looking at https://klarna.github.io/ui/#Input, I noticed that this icon is already appearing in the showroom. There should be no need to update the design, assuming it is the same as the one used in the Input example.

**Comment by JoakimLofgren** [comment]
Related issue then https://github.com/klarna/ui/issues/137 :)

**Comment by xaviervia** [comment]
I guess we should reject this one. I think it’s OK to repeat the icons: as we said somewhere else, they are just markup, not "assets".

**Comment by JoakimLofgren** [comment]
Yeah. And I actually wanted to use the Field anyways for the datepicker.

**Pull request closed without merging**
